name: Build

on:
  release:
    types: [created]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build Binaries
        run: |
          GOARCH=amd64 GOOS=linux go build -ldflags '-extldflags "-static"' -o openmhzpi-linux-amd64
          GOARCH=arm64 GOOS=linux go build -ldflags '-extldflags "-static"' -o openmhzpi-linux-arm64
          GOARCH=aarch64 GOOS=linux go build -ldflags '-extldflags "-static"' -o openmhzpi-linux-aarch64
          GOARCH=amd64 GOOS=windows go build -ldflags '-extldflags "-static"' -o openmhzpi-windows-amd64.exe

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./openmhzpi-linux-amd64
            ./openmhzpi-linux-arm64
            ./openmhzpi-linux-aarch64
            ./openmhzpi-windows-amd64.exe
