name: Build

on:
  release:
    types: [created]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build Binaries
        run: |
          GOARCH=arm64 GOOS=linux go build -ldflags '-extldflags "-static"' -o openmhzpi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./openmhzpi
